version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-authorization-token --region us-east-1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t project_2020_ecs_repo:latest .
      - docker tag project_2020_ecs_repo:latest 145696882850.dkr.ecr.us-east-1.amazonaws.com/project_2020_ecs_repo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 145696882850.dkr.ecr.us-east-1.amazonaws.com/project_2020_ecs_repo:latest